### ISSUE TITLE
Hydrate Orchestrator for pull model 

### ISSUE THREAD

**Issue by tonirvega** [prefapp/daggerverse#45]
# Motivation 

We need an orchestrator to hydrate different types of wet repositories, like:
- from Helm values to Kubernetes resources, 
- from TFWorkspaceClaim to FirestarterTFWorkspaces
- from AnsibleClaim to ...??
- from BicepClaim to ARM templates??

### Stack:
    - Kubernets 1.22+
    - dagger v0.14.0+

# Model architecture
![render-dagger-module drawio(1)](https://github.com/user-attachments/assets/e26319e6-e983-4b65-845f-3aeca5cc46d7)

# Flow chart 
![render-dagger-module drawio-flow-chart](https://github.com/user-attachments/assets/4b43f727-348a-498c-b4a0-22e42ebadd6e)

# Main function

## The main function will receive three principal parameters

1. Repository Directory: `repoDir *dagger.Directory`
  - The directory of the repository, where code is. 
2. AffectedPaths: `string` 
  - JSON format
  - Example: `["my-path/a", "my-path/b", "my-path/c"]`
3. AuthDirectory: `authDir *dagger.Directory`
  - The auth directory will contain the needed files with auth information to process by the specific
     hydrate processes. 
  - Example:
     - We need to authenticate against helm repository. 
```yaml
name: example
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    
      # LOGIN
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      # Prepare a folder with de auth data
      - run: |
          USER_NAME="00000000-0000-0000-0000-000000000000"
          PASSWORD=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken) 
          mkdir -p /tmp/authDir/az
          echo $PASSWORD >> /tmp/auth/az/helmlogin.txt
          echo $USER_NAME >> /tmp/auth/az/helmlogin.txt
          echo $ecr >> /tmp/auth/az/helmlogin.txt
      
      - uses: actions/checkout@v4
      
      - uses: prefapp/analyze-changes@v1
        id: analyze-changes
      
      # In this stage, we pass the auth data to the orchestrator, which will distribute the executions 
      # depending on the affected paths. 
      # Each specific implementation (HydrateKubernetes will handle the auth data 
      # to login against the helm repository)
      - run: | 
          dagger call \ 
           -m github.com/prefapp/daggerverse/hydrate-orchestrator@v1.0.0 \
           orchestrate-render \ 
           --affectedPaths={{ steps.analyze.changes.outputs.result }} \
           --repo-dir=./repo  \ 
           --authDir=/tmp/authDir
``` 
diagram: https://app.diagrams.net/?src=about#G1KiCY57g_N5B6txxDpM-eVw5R-vl9NQCr#%7B%22pageId%22%3A%22isT5--OD6I6HYCnsYudc%22%7D

### Tasks
- [ ] Create module structure
- [ ] Integrate module with HydrateKubernetes module prefapp/daggerverse#44
- [ ] Integrate module with Github module prefapp/daggerverse#46
- [ ] Tests have been passed
- [ ] https://github.com/prefapp/action-make-state-repos-dispatches/issues/21
- [ ] https://github.com/prefapp/daggerverse/issues/62
- [ ] https://github.com/prefapp/features/issues/320
- [ ] https://github.com/prefapp/gitops-k8s/issues/761

**Comment by alambike** [comment]
We agree the following workflows Redactor:


- Rename "hydrate-pr" to "PR-verify". It only has to templetize (`helfime template`) and check that renderizations finish successfully.
- ```
--run-changes => rename to --validate-changes
            --updated-deployments '["kubernetes/${{ inputs.cluster }}/${{ inputs.tenant }}/${{ inputs.environment }}"]'
```
- New option 
```

--generate_deployment
  --type=${{input.type}} # choice: kubernetes, terr
  --cluster= ${{input.cluster}} # Acepts glob patterns
  --tenant=${{input.tenant}}## Acepts glob patterns
  --environment= ${{input.environment}} ## acepts glob patterns
```
