### ISSUE TITLE
Github module

### ISSUE THREAD

**Issue by tonirvega** [prefapp/daggerverse#46]
# Motivaton 

We need a Github module that has the common methods to manage pull requests, comments, reviewers, labels.

Stack:
  - Typescript v5+
  - node 20+
  - dagger v0.14.0+
  
```[tasklist]
### Tasks
- [x] A function to publish a pull request
- [x] A function to publish a comment in a pull request
- [x] A function to add reviewers to a pull request
```
